### ISSUE TITLE
our outgoing messages queueing needs some love

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/libsignal-service-dotnet#14]
`SendMessage` (or rather `SendRequest`) calls throw an `IOException` if 10s have passed w/o receiving a sent confirmation. The message however will stay in the websocket's queue and be sent as soon as a reconnect succeeds.

We will never be able to solve this perfectly since sent confirmations may get lost and we have to assume the message was not sent, but we should get closer to the truth and stop trying to send a message after throwing an IOException.

**Comment by mitchcapper** [comment]
This does explain why I sometimes saw double sends.  Is the best option to block sendmessage task until we get a confirmation (or at least a much longer timeout?)

**Comment by Trolldemorted** [comment]
All signal clients except signal-windows and signal-cli should hide those double sends, though.

I am not sure a longer timeout is wise (as 10+ seconds should never happen without a broken network), and the sendmessage task currently is blocking until either the confirmation arrives or the timeout IOException is thrown. This reduces our throughput though, since we are not sending new messages until the old ones are confirmed or considered lost - if the performance impact is too grave, we will have to change this too.

**Comment by Trolldemorted** [comment]
We now handle the queues like libsignal-service-java, which might be racy but drops messages when the connection is interrupted
