### ISSUE TITLE
our incoming queue thinks in batches, but our canceltoken does not

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/libsignal-service-dotnet#15]
We should honor the canceltoken's status and change the interface to single items.

**Comment by golf1052** [comment]
Can you point to what needs to be fixed? I assume [this](https://github.com/signal-csharp/libsignal-service-dotnet/blob/master/libsignal-service-dotnet/SignalServiceMessagePipe.cs#L53-L80) may be involved?

**Comment by Trolldemorted** [comment]
Yeah, I think I exaggerated while thinking in batches of messages.

As a quick fix for the lost messages in S-W we could just break [here ](https://github.com/signal-csharp/Signal-Windows/blob/master/Signal-Windows/Signal/IncomingMessages.cs#L73) if a cancel-exception is thrown.
