### ISSUE TITLE
we should compare the messagedigest of attachments

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/libsignal-service-dotnet#2]

**Comment by Trolldemorted** [comment]
@golf1052 was this fixed by 5090d98e575ff67f8890d6ef5311e12a8cdd75a0?

**Comment by golf1052** [comment]
[Yes it was](https://github.com/signal-csharp/libsignal-service-dotnet/commit/5090d98e575ff67f8890d6ef5311e12a8cdd75a0#diff-3c14e635d6211a3c21172ecd7d1521c4R164)
