### ISSUE TITLE
trustManagers / TrustStore not used remove?

### ISSUE THREAD

**Issue by mitchcapper** [signal-csharp/libsignal-service-dotnet#20]
While there is a TrustStore interface that is required neither function in the interface is ever used.   Any reason to keep this around currently? Planned for future use?

**Comment by Trolldemorted** [comment]
I believe they are used for certificate pinning in libsignal-service-android, so I guess we can throw it out (cc @golf1052)

**Comment by Trolldemorted** [comment]
Should we use them to encapsulate #17?

**Comment by mitchcapper** [comment]
Up to you happy to try to re-work #17 into it if you want.

**Comment by Trolldemorted** [comment]
All occurrences of truststores should be gone now
