### ISSUE TITLE
Contact discovery service

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/libsignal-service-dotnet#37]
The commits
https://github.com/signalapp/libsignal-service-java/commit/69bd2076567d34b0df23fb161880e5bdd6e21452
https://github.com/signalapp/libsignal-service-java/commit/c06f838e29072090b8889a0103a3933b6de0a236
https://github.com/signalapp/libsignal-service-java/commit/f1c52e9aeac78c4bf3315a4a45b11db4247f2925

are not included yet.

**Comment by golf1052** [comment]
I've started working on this in [this branch](https://github.com/signal-csharp/libsignal-service-dotnet/tree/contact-discovery-service)
