### ISSUE TITLE
Missing attachment id

### ISSUE THREAD

**Issue by clemensott** [signal-csharp/libsignal-service-dotnet#39]
I can't donwload attachents which are send from the offical iOS and android app because the attachment id of the message is missing (value is 0), but attachments which are send from signal-widows have an id.

Message from iOS:
![Screenshot 2020-12-18 170722](https://user-images.githubusercontent.com/42971547/102635573-d06fa200-4153-11eb-9e37-3ca5c310e980.jpg)

Message from signal-windows:
![Screenshot 2020-12-18 170717](https://user-images.githubusercontent.com/42971547/102635569-cfd70b80-4153-11eb-8e52-a148df3892e7.jpg)

Any idea what is causing this?

**Comment by golf1052** [comment]
I've started looking at attachments. This PR https://github.com/signal-csharp/libsignal-service-dotnet/pull/45 goes over what is needed to get them working again.

**Comment by golf1052** [comment]
This has been fixed by https://github.com/signal-csharp/libsignal-service-dotnet/pull/45
