### ISSUE TITLE
get approval for GPLv3

### ISSUE THREAD

**Issue by Trolldemorted** [signal-csharp/libsignal-service-dotnet#4]
Since this project contains code and comments from several people, i'd like ask if you are ok with this being licensed under the GPLv3.

cc  @smndtrl, @langboost, @golf1052

**Comment by golf1052** [comment]
Don't most of the code files already have part of the GPLv3 license text in the header?
Sounds fine with me to make it official.

**Comment by Trolldemorted** [comment]
Most do, but not all, and i'd like to remove the gpl license text from the source files and instead have one for the project, similar to the official OWS libraries.

**Comment by smndtrl** [comment]
Feel free to put all of my signal related code (libtextsecure-uwp, libaxolotl-uwp, Signal-UWP) under the GPLv3. I'm happy that someone tries bringing Signal to Windows. I stopped my effort due to finishing university and starting a very demanding job.

**Comment by jeff-r-skillrev** [comment]
Same here, no objections, and hope that it proves a useful foundation for
you.

**Comment by Trolldemorted** [comment]
thanks for both your work and your approval for GPLv3!
