### ISSUE TITLE
Fatal: InvalidVersionException / Unsupported version! hard error on incoming messages

### ISSUE THREAD

**Issue by mitchcapper** [signal-csharp/libsignal-service-dotnet#43]
At first tried using just the libraries and thought it might be an issue with my callback code but just tried using the latest https://github.com/signal-csharp/Signal-Windows client and see the same error message in its logs so think it is a library error.  Is there a new version?

**Comment by mitchcapper** [comment]
Looking at our code throwing this: https://github.com/signal-csharp/libsignal-service-dotnet/blob/e676dd66dac6352eb4b6348b6b5414c368236f94/libsignal-service-dotnet/messages/SignalServiceEnvelope.cs#L48-L49

comparing with the source repo:
https://github.com/signalapp/Signal-Android/blob/2282cd12d7d72a7340903367cbac013b51a940e4/libsignal/service/src/main/java/org/whispersystems/signalservice/api/messages/SignalServiceEnvelope.java

https://github.com/signalapp/Signal-Android/blob/a324288d97efe4dfe5e7480b201cf79d49be46d0/libsignal/service/src/main/java/org/whispersystems/signalservice/api/messages/SignalServiceContent.java#L359-L365

They don't throw the error in the main class but only in SignalServiceContent.  

The current protocol version seems to be 6: https://github.com/signalapp/Signal-Android/blob/a324288d97efe4dfe5e7480b201cf79d49be46d0/libsignal/service/src/main/proto/SignalService.proto#L251

Looking deeper I think it may be that this library is not updated with the main libraries.   Reading the contributing this seems to line up with us around feb of 2019.  I will create another ticket around that.

**Comment by golf1052** [comment]
This appears to be the commit that broke us https://github.com/signalapp/Signal-Android/commit/29d66f2b926d46bff57f5bbd230d0757fe071c48#diff-c0bff1aa61fca2aa96f9a8952cadd4ad2f7e41f8745c8cde5900021fc956d018

It looks like simply removing the version check will fix this.

**Comment by golf1052** [comment]
Just tested it locally and it works. Literally as simple as removing the version check and passing `ciphertext` directly into the `Envelope.Parser.ParseFrom()`.

**Comment by golf1052** [comment]
This is fixed in [2.10.0.2](https://www.nuget.org/packages/libsignal-service-dotnet/2.10.0.2)
