### ISSUE TITLE
Is there any documentation on how to use the library?

### ISSUE THREAD

**Issue by SeppPenner** [signal-csharp/libsignal-service-dotnet#46]
Is there any documentation on how to use the library? I have some issues to transfer the code from https://github.com/signalapp/libsignal-service-java#readme to C#:

There are several issues in the code:
* `TrustStore` doesn't exist
* `generateLastResortPreKey` doesn't exist (However, it seems to be not needed in `SetPreKeysAsync` either?)
* `signedPreKeyId` is not set (This is an issue from the Java description as well as it isn't explained there either)
* `RequestSmsVerificationCodeAsync` --> What needs to be filled in as captcha token?
* `VerifyAccountWithCodeAsync` --> What to fill in for `fetchesMessages`, `pin`, `unidentifiedAccessKey` and `unrestrictedUnidentifiedAccess`?
* `generateRandomSignalingKey` doesn't exist (Can this really be just anything random?)
* `generateRandomInstallId` doesn't exist (Can this really be just anything random?)
* `gcmRegistrationId` / `REGISTRATION_ID` is not explained (This is an issue from the Java description as well as it isn't explained there either)

The same for the sending and receiving of messages. I have created a repository under https://github.com/SeppPenner/SimpleSignalClient. If someone could give me some hints there, it would be really appreciated ❤️

**Comment by LeadManPL** [comment]
Same question here. Where is some docs how to use this lib?

**Comment by golf1052** [comment]
We don't have any docs on the lib. The best way to know how to use it is by looking at the main app [Signal-Windows](https://github.com/signal-csharp/Signal-Windows)

**Comment by LeadManPL** [comment]
@golf1052 : well, thanks for the hint
