### ISSUE TITLE
usage example

### ISSUE THREAD

**Issue by mitchcapper** [signal-csharp/libsignal-service-dotnet#6]
Is there a usage example for this library?

**Comment by Trolldemorted** [comment]
sure!

https://github.com/signal-csharp/Signal-Windows

**Comment by mitchcapper** [comment]
oh wow!  Thanks @Trolldemorted  way further along than I thought.

**Comment by HTUlv412** [comment]
There is any documentation about how to send and listen simple byte[] messages?
